services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    profiles:
      - orphan-snapshot
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - assembly_apiaries_net

volumes:
  n8n_data:
    external: true

networks:
  assembly_apiaries_net:
    external: true
